###############    variables    ###############

CXX = c++
CFLAGS = -Wall -Wextra -Werror -g -std=c++98 -I./includes -I./libs -Ofast

SRC_DIR = ./srcs
OBJS_DIR = ./objs
OUTPUT_DIR ?= .
NAME ?= Mommy

###############    Files    ###############

SRC_GENERAL =	main \
				Bureaucrat \

SRC	= $(addprefix $(SRC_DIR)/, $(addsuffix .cpp,	$(SRC_GENERAL) \
))

OBJS	:= $(patsubst $(SRC_DIR)/%.cpp, $(OBJS_DIR)/%.o, $(SRC))

###############    Compilation    ###############
all: create_obj_dir $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CFLAGS) -o $(OUTPUT_DIR)/$(NAME) $(OBJS)

$(OBJS_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(CXX) $(CFLAGS) -o $@ -c $<

create_obj_dir :
	mkdir -p $(OBJS_DIR)

###############    Cleaning    ###############
clean:
	rm -rf $(OBJS_DIR)

fclean: clean
	rm -f $(NAME)

###############    Re    ###############
re: fclean all